services:
  nginx:
    container_name: nginx
    build:
      context: ./build/local
      dockerfile: Dockerfile_nginx
    ports:
      - "8001:80"
    volumes:
      - ./app/public:/app/public
    networks:
      - server_net
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./build/local
      dockerfile: Dockerfile_php
    networks:
      - server_net
    working_dir: /app
    volumes:
      - ./app:/app:delegated

  pgql:
    image: postgres:15.18
    container_name: pgql
    depends_on:
      - app
      - nginx
    networks:
      - server_net
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_ROOT_PASSWORD=secret
    ports:
      - "7001:5432"

volumes:
  db:
    driver: local

networks:
  server_net:
    driver: bridge